"""Add role_features table

Revision ID: 93b61b545486
Revises: e6c5c96db913
Create Date: 2026-06-26 16:48:32.879944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b61b545486'
down_revision: Union[str, None] = 'e6c5c96db913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('feature_key', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_role', 'feature_key', name='uq_role_feature_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_features')
    # ### end Alembic commands ###
