"""Add icon_name to Amenity

Revision ID: a41f618406b9
Revises: 93b61b545486
Create Date: 2026-07-01 14:20:05.677182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41f618406b9'
down_revision: Union[str, None] = '93b61b545486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('icon_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenities', 'icon_name')
    # ### end Alembic commands ###
